___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___


---

### 🧠 أولاً: ما هو **Topic Modeling**؟

**نمذجة المواضيع** (Topic Modeling) هي تقنية في معالجة اللغة الطبيعية (NLP) تُستخدم لاكتشاف المواضيع أو الأفكار الرئيسية **الخفية** داخل مجموعة كبيرة من المستندات النصية بدون إشراف (Unsupervised Learning).

🔹 **الفكرة:** كل مستند يحتوي على مجموعة من المواضيع، وكل موضوع يتم التعبير عنه بكلمات معينة تتكرر بشكل مميز فيه.

---

### 🎯 مثال بسيط:

نفترض عندنا 3 مقالات:

1. "القطط تحب النوم في الشمس"
2. "الكلاب وفية وتحب اللعب"
3. "أشعة الشمس مفيدة للنباتات والحيوانات"

بعد تطبيق Topic Modeling، يمكن أن نستنتج:

* **الموضوع 1:** متعلق بـ "الحيوانات الأليفة" ← (قطط، كلاب، تحب، لعب)
* **الموضوع 2:** متعلق بـ "الطبيعة/الشمس" ← (شمس، أشعة، مفيدة، نوم، نباتات)

---

### 📌 ما هو **LDA – Latent Dirichlet Allocation**؟

**LDA** هي أشهر خوارزمية في Topic Modeling، تعتمد على الاحتمالات.

🔹 **الفكرة:** كل مستند يحتوي على نسب معينة من المواضيع، وكل موضوع يحتوي على كلمات باحتمالات معينة.

🧪 **مثال:**
لو لدينا مستند يحتوي على كلمات: "شمس، قطط، نوم"،
LDA قد تقول إن هذا المستند:

* 60% موضوع الشمس
* 40% موضوع الحيوانات

والموضوع "الشمس" مثلاً يحتوي على كلمات مثل: "شمس، أشعة، نوم، حرارة"

---

### 📌 ما هو **NMF – Non-negative Matrix Factorization**؟

**NMF** طريقة أخرى لاكتشاف المواضيع لكنها تعتمد على تحليل المصفوفات الرياضية بدلاً من الاحتمالات.

🔹 يتم تحويل النصوص إلى مصفوفة (مثل TF-IDF)، ثم يتم **تفكيكها** إلى مصفوفتين:

* واحدة تمثل **المستندات مقابل المواضيع**
* الأخرى تمثل **المواضيع مقابل الكلمات**

🧪 **مثال:**
لو عندك مصفوفة تمثل 10 مستندات × 1000 كلمة،
NMF يحللها إلى:

* 10 مستندات × 5 مواضيع
* 5 مواضيع × 1000 كلمة

🔸 من خلالها نعرف كل مستند يتكلم عن أي موضوع، وكل موضوع يتكون من أي كلمات.

---

### 🆚 الفرق بين LDA و NMF:

| المقارنة    | LDA                        | NMF                           |
| ----------- | -------------------------- | ----------------------------- |
| نوع النموذج | احتمالي (Probabilistic)    | جبري (Matrix Factorization)   |
| مناسب لـ    | البيانات الكبيرة والمعقدة  | البيانات المتوسطة والصغيرة    |
| النتائج     | تكون أكثر "غموضاً" أحيانًا | أوضح لكن أقل "تنوعًا" أحيانًا |

---


# Latent Dirichlet Allocation

## Data

We will be using articles from NPR (National Public Radio), obtained from their website [www.npr.org](http://www.npr.org)

In [2]:
import pandas as pd

In [4]:
npr = pd.read_csv('npr.csv')

In [6]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

Notice how we don't have the topic of the articles! Let's use LDA to attempt to figure out clusters of the articles.

## Preprocessing

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

**`max_df`**` : float in range [0.0, 1.0] or int, default=1.0`<br>
When building the vocabulary ignore terms that have a document frequency strictly higher than the given threshold (corpus-specific stop words). If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

**`min_df`**` : float in range [0.0, 1.0] or int, default=1`<br>
When building the vocabulary ignore terms that have a document frequency strictly lower than the given threshold. This value is also called cut-off in the literature. If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

In [10]:
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [12]:
dtm = cv.fit_transform(npr['Article'])

In [13]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

## LDA

In [16]:
from sklearn.decomposition import LatentDirichletAllocation

In [18]:
LDA = LatentDirichletAllocation(n_components=7 , random_state=42)

In [22]:
# This can take awhile, we're dealing with a large amount of documents!
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

## Showing Stored Words

In [36]:
cv.get_feature_names_out()[50000]


'transcribe'

In [38]:
cv.get_feature_names_out()[0]


'00'

In [40]:
len(cv.get_feature_names_out())

54777

In [42]:
import random

In [48]:
for i in range(10):
    random_word_id = random.randint(0,54776)
    print(cv.get_feature_names_out()[random_word_id])

sabbaticals
superfans
horvath
mints
madeira
wemple
suv
compensated
robin
guangzhou


In [54]:
for i in range(10):
    random_word_id = random.randint(0,54776)
    print(cv.get_feature_names_out()[random_word_id])

employees
testimonies
milling
talkers
profound
turpin
boisjoly
mon
peppercorns
homogeneous


### Showing Top Words Per Topic

In [46]:
len(LDA.components_)

7

In [47]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [70]:
len(LDA.components_[0])

54777

In [74]:
LDA.components_[0]

array([8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
       1.43006821e-01, 1.42902042e-01, 1.42861626e-01])

In [76]:
single_topic = LDA.components_[0]

In [80]:
# Returns the indices that would sort this array.
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [82]:
# Word least representative of this topic
single_topic[2475]

0.1428571430851871

In [84]:
# Word most representative of this topic
single_topic[42993]

6247.245510521065

In [88]:
# Top 10 words for this topic:
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [90]:
top_word_indices = single_topic.argsort()[-10:]

In [92]:
for index in top_word_indices:
    print(cv.get_feature_names_out()[index])

new
percent
government
company
million
care
people
health
said
says


These look like business articles perhaps... Let's confirm by using .transform() on our vectorized articles to attach a label number. But first, let's view all the 10 topics found.

In [96]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


THE TOP 15 WORDS FOR TOPIC #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


THE TOP 15 WORDS FOR TOPIC #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


THE TOP 15 WORDS FOR TOPIC #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']


THE TOP 15 WORDS FOR TOPIC #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']


THE TOP 15 WORDS FOR TOPIC #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think',

### Attaching Discovered Topic Labels to Original Articles

In [116]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [118]:
dtm.shape

(11992, 54777)

In [120]:
len(npr)

11992

In [114]:
topic_results = LDA.transform(dtm)

In [122]:
topic_results.shape

(11992, 7)

In [124]:
topic_results[0]

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [126]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [128]:
topic_results[0].argmax()

1

This means that our model thinks that the first article belongs to topic #1.

### Combining with Original Data

In [130]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [66]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 0], dtype=int64)

In [132]:
len(topic_results.argmax(axis=1))

11992

In [134]:
npr['Topic'] = topic_results.argmax(axis=1)

In [136]:
npr.head(10)

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      1
4  From photography, illustration and video, to d...      2
5  I did not want to join yoga class. I hated tho...      3
6  With a   who has publicly supported the debunk...      3
7  I was standing by the airport exit, debating w...      2
8  If movies were trying to be more realistic, pe...      3
9  Eighteen years ago, on New Year’s Eve, David F...      2

## Great work!